version: '3.4'

services:
  api:
    image: ghcr.io/gcandez/gh/api
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=https://+:443
      - GH_DATABASE__HOST
      - GH_DATABASE__USER
      - GH_DATABASE__PASSWORD
      - GH_DATABASE__DATABASE
    ports:
      - "443:443"
