name: .NET Deploys

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    name: publish ${{ matrix.image }}

    strategy:
      matrix:
        image: [api]
        include:
          - image: api
            dockerfileDir: ./GH.Api
            imageName: api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup variables
        run: |       
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfileDir }}/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO }}/${{ matrix.imageName }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.REDEPLOY_WEBHOOK }}
