name: .NET Deploys

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup variables
        run: |       
          echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.dockerfileDir }}
          push: true
          tags: ghcr.io/${{ env.REPO }}/api
          cache-from: type=gha
          cache-to: type=gha,mode=max